# Generated by Django 4.2.30 on 2026-05-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_finalize_employee_position_and_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(check=models.Q(('base_salary__gte', 0)), name='position_base_salary_non_negative'),
        ),
    ]
