# Generated by Django 4.2.30 on 2026-05-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_position_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='needs_profile_update',
            field=models.BooleanField(default=False),
        ),
    ]
